class AllVolumesRemovedError:
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...

class DimensionError:
    def __init__(self, file_dimension: int, required_dimension: int) -> None: ...
    def __str__(self) -> str: ...
    def increment_stack_counter(self) -> None: ...
    @property
    def message(self) -> str: ...
