def _open_in_browser(content: bytes) -> None: ...
def set_max_img_views_before_warning(new_value: int | None) -> None: ...

class HTMLDocument:
    def __init__(self, html: str, width: int = ..., height: int = ...) -> None: ...
    def _check_n_open(self) -> None: ...
    def _repr_html_(self) -> str: ...
    def _repr_mimebundle_(self, include: None = ..., exclude: None = ...) -> dict[str, str]: ...
    def get_iframe(self, width: None = ..., height: None = ...) -> str: ...
    def get_standalone(self) -> str: ...
    def open_in_browser(self, file_name: str | None = ..., temp_file_lifetime: float | str = ...) -> None: ...
    def save_as_html(self, file_name: str) -> None: ...
