from typing import (
    Callable,
)

from nibabel.nifti1 import Nifti1Image

def on_windows_with_old_mpl_and_new_numpy() -> bool: ...
def with_memory_profiler(func: Callable) -> Callable: ...
def write_imgs_to_path(
    *imgs, file_path=..., create_files=..., use_wildcards=...
) -> Nifti1Image | list[str] | str | tuple[Nifti1Image, Nifti1Image]: ...
