def all_classes(
    return_private: bool = ..., modules_to_ignore: list[str] | None = ..., modules_to_consider: list[str] | None = ...
): ...
def all_functions(
    return_private: bool = ..., modules_to_ignore: list[str] | None = ..., modules_to_consider: list[str] | None = ...
): ...
def all_modules(modules_to_ignore: list[str] | None = ..., modules_to_consider: list[str] | None = ...): ...
